config/routes.rb
Spree::Core::Engine.routes.draw do

  post '/orders/:number/repeated_order' => 'repeated_orders#create', as: :repeat_order
  post '/admin/orders/:number/repeated_order/' => 'admin/repeated_orders#create', as: :admin_repeat_order

end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do

  def duplicate
    self.dup
  end

  def reload_price
    if variant
      self.price = variant.price
      self.cost_price = variant.cost_price
      self.currency = variant.currency
    end
  end

end

app/controllers/spree/admin/repeated_orders_controller.rb
module Spree
  module Admin
    class RepeatedOrdersController < Spree::Admin::BaseController

      include Spree::SpreeRepeatedOrder::ControllerHelpers::RepeatedOrder

      def create
        past_order = Spree::Order.find_by(number: params[:number])
        new_order = Spree::Order.new
        new_order.save

        duplicate_order(past_order, new_order)
        duplicate_address(past_order, new_order)

        last_incomplete_order = new_order.user.last_incomplete_spree_order

        success = true
        success = success && !past_order.completed_at.blank?
        success = success && new_order.generate_number #forcing number generation since we are skipping validation
        success = success && new_order.save(validate: false)
        success = success && merge_with_current_order(new_order, last_incomplete_order)

        if success
          flash[:success] = "The order has been duplicated. The new order id is #{new_order.number}"
          redirect_to(admin_orders_path)
        else
          flash[:error] = 'Oops.. something went wrong and the order could not be duplicated'
          redirect_to(edit_admin_order_path(past_order.number))
        end

      end

      private

      def merge_with_current_order(new_order, last_incomplete_order)
        if last_incomplete_order
          new_order.merge!(last_incomplete_order, new_order.user)
          new_order.save(validate: false)
        else
          true
        end
      end

      def duplicate_address(past_order, new_order)
        new_order.email = past_order.email
        new_order.user = past_order.user

        new_ship_address = past_order.ship_address.dup
        new_order.ship_address = new_ship_address
        new_bill_address = past_order.bill_address.dup
        new_order.bill_address = new_bill_address

        duplicate_extension(past_order, new_order)
      end

      def duplicate_extension(past_order, new_order)
        #do nothing - only here so it can be overriden
      end

    end
  end
end

app/controllers/spree/repeated_orders_controller.rb
module Spree
  class RepeatedOrdersController < Spree::StoreController

    include Spree::SpreeRepeatedOrder::ControllerHelpers::RepeatedOrder

    before_filter :check_authorization

    def create
      past_order = Spree::Order.find_by(number: params[:number])
      new_order = current_order(create_order_if_necessary: true)

      duplicate_order(past_order, new_order)

      if new_order.save
        new_order.contents.update_cart({})
        flash[:success] = 'We have added your past order items to the cart. Just proceed to checkout to complete it.'
      else
        flash[:error] = 'We are sorry, but we could not add your past items to the cart.'
      end

      redirect_to(cart_path)
    end

    private

    def check_authorization
      session[:access_token] ||= params[:token]

      order = Spree::Order.find_by_number(params[:number])
      authorize! :edit, order, session[:access_token]
    end

  end
end

app/views/spree/admin/orders/_repeat_button.haml
- if @order and @order.completed_at?
  = button_link_to Spree.t(:repeat_order), spree.admin_repeat_order_path(@order.number), method: :post, icon: 'fa fa fa-copy'

app/views/spree/users/_my_account_table.haml
%table.order-summary
  %thead
    %tr
      %th.order-number
        = Spree.t(:order_number)
      %th.order-date
        = Spree.t(:order_date)
      %th.order-status
        = Spree.t(:status)
      %th.order-payment-state
        = Spree.t(:payment_state)
      %th.order-shipment-state
        = Spree.t(:shipment_state)
      %th.order-total
        = Spree.t(:total)
      %th
  %tbody
    - @orders.each do |order|
      %tr
        %td.order-number
          = link_to order.number, order_url(order)
        %td.order-date
          = l order.completed_at.to_date
        %td.order-status
          = Spree.t("order_state.#{order.state}").titleize
        %td.order-payment-state
          = Spree.t("payment_states.#{order.payment_state}").titleize if order.payment_state
        %td.order-shipment-state
          = Spree.t("shipment_states.#{order.shipment_state}").titleize if order.shipment_state
        %td.order-total
          = order.display_total
        %td.repeat-order
          = form_tag repeat_order_path(order.number), method: :post do
            .fields
              = button_tag :class => 'large primary add-button', :type => :submit do
                = Spree.t(:repeat_order)